import { FormEvent, useState } from "react";
import { Badge, PageHeader } from "../../components/UI";
import { useApp } from "../../context/AppContext";
import { Level } from "../../types";

export default function TrainerProfile(){
  const {db,currentUser,updateTrainerProfile}=useApp();const trainer=db.trainers.find(t=>t.userId===currentUser?.id);
  const [form,setForm]=useState(()=>({qualification:trainer?.qualification||"",experienceYears:trainer?.experienceYears||0,subjects:trainer?.subjects.join(", ")||"",skills:trainer?.skills.join(", ")||"",level:(trainer?.level||"Beginner") as Level,certifications:trainer?.certifications.join(", ")||"",availability:trainer?.availability||"Available",bio:trainer?.bio||""}));
  if(!trainer)return <div className="panel">Trainer profile not available.</div>;
  const submit=(e:FormEvent)=>{e.preventDefault();updateTrainerProfile({qualification:form.qualification,experienceYears:Number(form.experienceYears),subjects:form.subjects.split(",").map(x=>x.trim()).filter(Boolean),skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),level:form.level,certifications:form.certifications.split(",").map(x=>x.trim()).filter(Boolean),availability:form.availability as any,bio:form.bio})};
  return <><PageHeader title="Professional Profile" subtitle="Maintain qualification, expertise and availability for Admin verification." actions={trainer.verified?<Badge tone="green">Admin Verified</Badge>:<Badge tone="amber">Verification pending</Badge>}/>
    <section className="panel profile-panel"><form className="stack-form" onSubmit={submit}><div className="form-grid two"><label>Qualification<input value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/></label><label>Experience (years)<input type="number" min={0} value={form.experienceYears} onChange={e=>setForm({...form,experienceYears:Number(e.target.value)})}/></label><label>Subjects of expertise<input value={form.subjects} onChange={e=>setForm({...form,subjects:e.target.value})} placeholder="Comma separated"/></label><label>Competency level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value as Level})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Skills<input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Comma separated"/></label><label>Certifications<input value={form.certifications} onChange={e=>setForm({...form,certifications:e.target.value})} placeholder="Comma separated"/></label><label>Availability<select value={form.availability} onChange={e=>setForm({...form,availability:e.target.value as any})}><option>Available</option><option>Limited</option><option>Unavailable</option></select></label></div><label>Professional biography<textarea rows={5} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label><button className="btn btn-primary">Save professional profile</button></form></section>
  </>
}