import { FormEvent, useState } from "react";
import { Badge, PageHeader } from "../../components/UI";
import { useApp } from "../../context/AppContext";
import { Level } from "../../types";

export default function TrainerCourses(){
  const {db,currentUser,createCourse}=useApp();const trainer=db.trainers.find(t=>t.userId===currentUser?.id);
  const courses=db.courses.filter(c=>c.trainerId===trainer?.id);
  const [form,setForm]=useState({title:"",code:"",department:trainer?.department||"",subject:trainer?.subjects[0]||"",level:"Intermediate" as Level,description:"",objectives:"",durationHours:12,startDate:"",endDate:"",enrollmentLimit:30});
  const submit=(e:FormEvent)=>{e.preventDefault();if(!trainer)return;createCourse({title:form.title,code:form.code,department:form.department,subject:form.subject,level:form.level,trainerId:trainer.id,description:form.description,objectives:form.objectives.split("\n").map(x=>x.trim()).filter(Boolean),durationHours:Number(form.durationHours),startDate:form.startDate,endDate:form.endDate,enrollmentLimit:Number(form.enrollmentLimit),modules:[{id:`m-${Date.now()}`,title:"Module 1",lessons:[{id:`l-${Date.now()}`,title:"Introduction",type:"video",durationMin:20,resource:"Upload after approval"}]}]});setForm({...form,title:"",code:"",description:"",objectives:""})};
  return <><PageHeader title="Course & Content Management" subtitle="Create structured course proposals and send them for Admin approval."/>
    <div className="dashboard-grid content-layout"><section className="panel"><div className="panel-head"><div><h3>Create course proposal</h3><p>Admin review is required before publishing</p></div></div><form className="stack-form" onSubmit={submit}><div className="form-grid two"><label>Course title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Course code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required placeholder="CC-XXX-101"/></label><label>Department<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} required/></label><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></label><label>Level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value as Level})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Duration (hours)<input type="number" min={1} value={form.durationHours} onChange={e=>setForm({...form,durationHours:Number(e.target.value)})}/></label><label>Start date<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} required/></label><label>End date<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} required/></label><label>Enrollment limit<input type="number" min={1} value={form.enrollmentLimit} onChange={e=>setForm({...form,enrollmentLimit:Number(e.target.value)})}/></label></div><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label>Objectives (one per line)<textarea rows={3} value={form.objectives} onChange={e=>setForm({...form,objectives:e.target.value})}/></label><button className="btn btn-primary">Send for Admin approval</button></form></section>
    <section className="panel"><div className="panel-head"><div><h3>My courses</h3><p>{courses.length} total</p></div></div><div className="notification-list">{courses.map(c=><article key={c.id}><div><Badge tone={c.status==="published"?"green":c.status==="pending"?"amber":"gray"}>{c.status}</Badge><Badge tone="blue">{c.level}</Badge></div><h4>{c.title}</h4><p>{c.description}</p><small>{c.startDate} → {c.endDate}</small></article>)}</div></section></div>
  </>
}