import { FormEvent, useState } from "react";
import { Badge, PageHeader } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function TrainerAssessments(){
  const {db,currentUser,addAssessment}=useApp();const trainer=db.trainers.find(t=>t.userId===currentUser?.id);const courses=db.courses.filter(c=>c.trainerId===trainer?.id);
  const [form,setForm]=useState({courseId:courses[0]?.id||"",type:"post" as "pre"|"post"|"competency",title:"",subject:courses[0]?.subject||"",passingPercentage:70,durationMin:10,deadline:"2026-10-15",question:"",a:"",b:"",c:"",d:"",answer:0,competency:""});
  const submit=(e:FormEvent)=>{e.preventDefault();addAssessment({courseId:form.courseId,type:form.type,title:form.title,subject:form.subject,passingPercentage:Number(form.passingPercentage),durationMin:Number(form.durationMin),deadline:form.deadline,questions:[{id:`q-${Date.now()}`,text:form.question,options:[form.a,form.b,form.c,form.d],answer:Number(form.answer),competency:form.competency||form.subject}]});setForm({...form,title:"",question:"",a:"",b:"",c:"",d:"",competency:""})};
  const mine=db.assessments.filter(a=>courses.some(c=>c.id===a.courseId));
  return <><PageHeader title="Assessment Management" subtitle="Create subject-wise MCQ assessments and review trainee attempts."/>
    <div className="dashboard-grid content-layout"><section className="panel"><div className="panel-head"><div><h3>Create MCQ assessment</h3><p>Prototype supports one-question creation per submission</p></div></div><form className="stack-form" onSubmit={submit}><label>Course<select value={form.courseId} onChange={e=>{const c=courses.find(x=>x.id===e.target.value);setForm({...form,courseId:e.target.value,subject:c?.subject||form.subject})}}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div className="form-grid two"><label>Assessment title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as any})}><option value="pre">Pre-training</option><option value="post">Post-training</option><option value="competency">Competency</option></select></label><label>Passing %<input type="number" value={form.passingPercentage} onChange={e=>setForm({...form,passingPercentage:Number(e.target.value)})}/></label><label>Duration (min)<input type="number" value={form.durationMin} onChange={e=>setForm({...form,durationMin:Number(e.target.value)})}/></label><label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} required/></label></div><label>Question<input value={form.question} onChange={e=>setForm({...form,question:e.target.value})} required/></label><div className="form-grid two"><label>Option A<input value={form.a} onChange={e=>setForm({...form,a:e.target.value})} required/></label><label>Option B<input value={form.b} onChange={e=>setForm({...form,b:e.target.value})} required/></label><label>Option C<input value={form.c} onChange={e=>setForm({...form,c:e.target.value})} required/></label><label>Option D<input value={form.d} onChange={e=>setForm({...form,d:e.target.value})} required/></label><label>Correct answer<select value={form.answer} onChange={e=>setForm({...form,answer:Number(e.target.value)})}><option value={0}>A</option><option value={1}>B</option><option value={2}>C</option><option value={3}>D</option></select></label><label>Competency measured<input value={form.competency} onChange={e=>setForm({...form,competency:e.target.value})}/></label></div><button className="btn btn-primary">Create assessment</button></form></section>
      <section className="panel"><div className="panel-head"><div><h3>My assessments</h3><p>{mine.length} available</p></div></div><div className="notification-list">{mine.map(a=><article key={a.id}><div><Badge tone="blue">{a.type}</Badge><Badge tone="green">Pass {a.passingPercentage}%</Badge></div><h4>{a.title}</h4><p>{a.subject} · {a.questions.length} questions · {a.durationMin} min{a.deadline?` · Due ${a.deadline}`:""}</p><small>{db.attempts.filter(x=>x.assessmentId===a.id).length} attempts</small></article>)}</div></section></div>
  </>
}