import { Award, CheckCircle2, FileCheck2, Gauge, QrCode, ShieldCheck } from "lucide-react";
import { Badge, PageHeader, ProgressBar, StatCard } from "../../components/UI";
import { useApp } from "../../context/AppContext";
import { operationalReadiness } from "../../utils/engine";

export default function CapabilityPassport(){
  const {db,currentUser}=useApp();const trainee=db.trainees.find(t=>t.userId===currentUser?.id);if(!trainee)return null;
  const ready=operationalReadiness(db,trainee.id);const certs=db.certificates.filter(c=>c.traineeId===trainee.id);const evidence=db.evidence.filter(e=>e.traineeId===trainee.id);const results=db.competencyResults.filter(r=>r.traineeId===trainee.id);const scenarios=db.scenarioAttempts.filter(a=>a.traineeId===trainee.id);
  return <><PageHeader title="Verified Capability Passport" subtitle="A portable, evidence-backed record of what you are ready to do—not just the courses you completed." actions={<button className="btn btn-secondary" onClick={()=>window.print()}>Print / Save PDF</button>}/>
    <section className="passport-hero"><div className="passport-id"><div className="passport-avatar">{trainee.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><span className="eyebrow">MOES / IMD · CAPACITY CONNECT</span><h2>{trainee.name}</h2><p>{trainee.designation} · {trainee.department}</p><Badge tone="green"><ShieldCheck size={13}/> Evidence-backed record</Badge></div></div><div className="passport-readiness"><div className="readiness-circle"><strong>{ready.score}</strong><span>ORI / 100</span></div><div><b>{ready.band}</b><span>Operational Readiness Index</span></div></div><div className="passport-qr"><QrCode/><span>Verification placeholder</span><strong>CC-PASS-{trainee.id.toUpperCase()}</strong></div></section>
    <div className="stats-grid compact"><StatCard label="Verified Competencies" value={results.filter(r=>r.gapText==="Required level met").length} icon={<CheckCircle2/>}/><StatCard label="Verified Evidence" value={evidence.filter(e=>e.status==="verified").length} icon={<FileCheck2/>}/><StatCard label="Scenario Attempts" value={scenarios.length} icon={<Gauge/>}/><StatCard label="Certificates" value={certs.length} icon={<Award/>}/></div>
    <section className="panel"><div className="panel-head"><div><h3>Readiness composition</h3><p>Transparent evidence behind the ORI score.</p></div></div><div className="readiness-breakdown"><div><span>Competency baseline</span><b>{ready.competency}/30</b><ProgressBar value={ready.competency/30*100}/></div><div><span>Learning completion</span><b>{ready.learning}/15</b><ProgressBar value={ready.learning/15*100}/></div><div><span>Assessment performance</span><b>{ready.assessment}/25</b><ProgressBar value={ready.assessment/25*100}/></div><div><span>Verified evidence</span><b>{ready.evidence}/15</b><ProgressBar value={ready.evidence/15*100}/></div><div><span>Operational scenarios</span><b>{ready.scenario}/15</b><ProgressBar value={ready.scenario/15*100}/></div></div></section>
    <div className="dashboard-grid two"><section className="panel"><div className="panel-head"><div><h3>Competency record</h3><p>Current role-based capability status</p></div></div><div className="passport-list">{results.map(r=><article key={r.id}><div><strong>{r.subject}</strong><span>{r.role}</span></div><div><Badge tone={r.gapText==="Required level met"?"green":"amber"}>{r.currentLevel}</Badge><small>{r.score}% · target {r.requiredLevel}</small></div></article>)}</div></section><section className="panel"><div className="panel-head"><div><h3>Operational evidence ledger</h3><p>Trainer-reviewed proof of application</p></div></div><div className="passport-list">{evidence.map(e=><article key={e.id}><div><strong>{e.title}</strong><span>{e.type} · {e.subject}</span></div><div><Badge tone={e.status==="verified"?"green":e.status==="revision"?"red":"amber"}>{e.status}</Badge>{e.score!==undefined&&<small>{e.score}/100</small>}</div></article>)}</div></section></div>
    <section className="panel"><div className="panel-head"><div><h3>Verifiable credentials</h3><p>Competency credentials include a validity window for future recertification.</p></div></div><div className="passport-list credential-list">{certs.map(c=>{const course=db.courses.find(x=>x.id===c.courseId);return <article key={c.id}><div><Award/><div><strong>{c.competency}</strong><span>{course?.title} · {c.certificateCode}</span></div></div><div><Badge tone="green">Verified</Badge><small>Issued {c.issuedAt}{c.validUntil?` · valid to ${c.validUntil}`:""}</small></div></article>})}{!certs.length&&<p className="muted-copy">No verified certificates yet. Complete the full capability verification workflow to earn one.</p>}</div></section>
  </>
}
