import { FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Badge, PageHeader } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function CompetencyCheck(){
  const {db,currentUser,runCompetencyCheck}=useApp();const nav=useNavigate();const trainee=db.trainees.find(t=>t.userId===currentUser?.id);
  const competencyAssessments=db.assessments.filter(a=>a.type==="competency");
  const [assessmentId,setAssessmentId]=useState(competencyAssessments[0]?.id||"");const assessment=db.assessments.find(a=>a.id===assessmentId);
  const [answers,setAnswers]=useState<number[]>([]);const [result,setResult]=useState<any>(null);
  const submit=(e:FormEvent)=>{e.preventDefault();if(!assessment||!trainee)return;const correct=assessment.questions.reduce((s,q,i)=>s+(answers[i]===q.answer?1:0),0);const score=Math.round(correct/assessment.questions.length*100);const missed=assessment.questions.filter((q,i)=>answers[i]!==q.answer).map(q=>q.competency);const r=runCompetencyCheck(trainee.designation,assessment.subject,score,[...new Set(missed)]);setResult(r)};
  return <><PageHeader title="Competency Check" subtitle="Measure your current level against the competency required for your role."/>
    {!result?<section className="panel assessment-shell"><div className="assessment-intro"><div><span>Step 1 of 3</span><h3>Select role-based assessment</h3><p>Your current designation is <strong>{trainee?.designation}</strong>. The prototype compares your score with the mapped role requirement.</p></div><select value={assessmentId} onChange={e=>{setAssessmentId(e.target.value);setAnswers([])}}>{competencyAssessments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></div>
      {assessment&&<form onSubmit={submit}><div className="assessment-meta"><Badge tone="blue">{assessment.subject}</Badge><span>{assessment.questions.length} questions</span><span>{assessment.durationMin} min</span></div>{assessment.questions.map((q,i)=><fieldset className="question-card" key={q.id}><legend><span>{i+1}</span>{q.text}</legend>{q.options.map((o,j)=><label className={answers[i]===j?"selected":""} key={o}><input type="radio" name={q.id} checked={answers[i]===j} onChange={()=>{const next=[...answers];next[i]=j;setAnswers(next)}} required/>{o}</label>)}</fieldset>)}<button className="btn btn-primary" disabled={answers.filter(x=>x!==undefined).length!==assessment.questions.length}>Submit competency check</button></form>}</section>
    :<section className="panel result-panel"><div className="result-score"><strong>{result.score}%</strong><span>Current competency score</span></div><div><Badge tone="amber">{result.currentLevel}</Badge><h2>{result.subject}</h2><p>Required level: <strong>{result.requiredLevel}</strong></p><h3>{result.gapText}</h3><p>Missing competencies identified:</p><div className="chip-row">{result.missingCompetencies.length?result.missingCompetencies.map((x:string)=><span className="chip" key={x}>{x}</span>):<Badge tone="green">No gap identified</Badge>}</div><div className="result-actions"><button className="btn btn-secondary" onClick={()=>setResult(null)}>Retake</button><button className="btn btn-primary" onClick={()=>nav("/trainee/recommendations")}>See personalized recommendations</button></div></div></section>}
  </>
}