import { BookOpen, CheckCircle2, FileText, PlayCircle, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useState } from "react";
import { EvidenceItem } from "../../types";
import { Badge, EmptyState, PageHeader, ProgressBar } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function LearningPage(){
  const {courseId}=useParams();const {db,currentUser,toggleLesson,submitEvidence,submitFeedback}=useApp();
  const [evidenceTitle,setEvidenceTitle]=useState("");const [evidenceType,setEvidenceType]=useState<EvidenceItem["type"]>("Operational Task");const [rating,setRating]=useState(5);const [feedback,setFeedback]=useState("");const trainee=db.trainees.find(t=>t.userId===currentUser?.id);const enrollments=db.enrollments.filter(e=>e.traineeId===trainee?.id&&["approved","completed"].includes(e.status));
  const enrollment=courseId?enrollments.find(e=>e.courseId===courseId):undefined;const course=enrollment?db.courses.find(c=>c.id===enrollment.courseId):undefined; const mappedResources=course?db.resources.filter(r=>r.courseId===course.id&&(r.status||"published")==="published"):[];
  if(!courseId)return <><PageHeader title="My Learning" subtitle="Approved courses, modules, resources and progress."/><div className="learning-grid">{enrollments.map(e=>{const c=db.courses.find(x=>x.id===e.courseId)!;return <article className="learning-card" key={e.id}><div className="learning-cover"><BookOpen/></div><div><Badge tone={e.status==="completed"?"green":"blue"}>{e.status}</Badge><h3>{c.title}</h3><p>{c.description}</p><div className="progress-label"><span>Progress</span><b>{e.progress}%</b></div><ProgressBar value={e.progress}/><Link className="btn btn-primary btn-block" to={`/trainee/learning/${c.id}`}>Open course</Link></div></article>})}{!enrollments.length&&<EmptyState title="No approved courses yet" body="Request enrollment from Recommendations and wait for Admin approval."/>}</div></>;
  if(!course||!enrollment)return <EmptyState title="Course unavailable" body="This course is not currently approved for your trainee account."/>;
  return <><PageHeader title={course.title} subtitle={`${course.code} · ${course.level} · ${course.durationHours} hours`} actions={<Link className="btn btn-secondary" to="/trainee/learning">Back to courses</Link>}/>
    <section className="course-hero"><div><Badge tone="green">{enrollment.status}</Badge><h2>{course.description}</h2><p>{course.objectives.join(" · ")}</p></div><div><strong>{enrollment.progress}%</strong><span>completed</span><ProgressBar value={enrollment.progress}/></div></section>
    <div className="course-learning-layout"><section><div className="video-placeholder"><PlayCircle/><strong>Recorded lecture player</strong><span>Select a video lesson to preview learning content.</span></div>{course.modules.map((m,mi)=><article className="module-card" key={m.id}><h3>Module {mi+1}: {m.title}</h3>{m.lessons.map(l=>{const done=enrollment.completedLessonIds.includes(l.id);return <div className={`lesson-row ${done?"done":""}`} key={l.id}><div className="lesson-type">{l.type==="video"?<PlayCircle/>:<FileText/>}</div><div><strong>{l.title}</strong><span>{l.type} · {l.durationMin} min · {l.resource}</span></div><button className={done?"btn btn-success-soft":"btn btn-secondary"} onClick={()=>toggleLesson(course.id,l.id)}>{done?<><CheckCircle2 size={16}/> Completed</>:"Mark complete"}</button></div>})}</article>)}{mappedResources.length>0&&<article className="module-card"><h3>Mapped IMD Learning Resources</h3>{mappedResources.map(r=><div className="lesson-row" key={r.id}><div className="lesson-type"><FileText/></div><div><strong>{r.title}</strong><span>{r.type} · {r.competency||r.subject} · {r.level}</span></div>{r.dataUrl?<a className="btn btn-secondary" href={r.dataUrl} target="_blank" download={r.downloadable?r.fileName:undefined}>Open</a>:r.externalUrl?<a className="btn btn-secondary" href={r.externalUrl} target="_blank" rel="noreferrer">Open</a>:<Badge tone="gray">Library item</Badge>}</div>)}</article>}</section>
      <aside className="panel sticky-panel"><h3>Course progress</h3><div className="big-progress">{enrollment.progress}%</div><ProgressBar value={enrollment.progress}/><p>Complete all lessons, then pass the post-training assessment before competency verification.</p><Link className="btn btn-primary btn-block" to="/trainee/assessments">Go to assessments</Link><div className="capability-evidence-box"><div className="evidence-title"><ShieldCheck size={18}/><div><strong>Capability Evidence</strong><span>Required before final competency verification</span></div></div><select value={evidenceType} onChange={e=>setEvidenceType(e.target.value as EvidenceItem["type"])}><option>Operational Task</option><option>Simulation</option><option>Case Report</option><option>Dataset Review</option></select><input value={evidenceTitle} onChange={e=>setEvidenceTitle(e.target.value)} placeholder="Evidence title / task completed"/><button className="btn btn-secondary btn-block" disabled={!evidenceTitle.trim()} onClick={()=>{submitEvidence(course.id,evidenceTitle,evidenceType);setEvidenceTitle("")}}>Submit evidence</button><small>{db.evidence.filter(e=>e.traineeId===trainee?.id&&e.courseId===course.id).length} evidence item(s) submitted</small></div><div className="course-feedback-box"><strong>Course feedback</strong><div className="feedback-rating"><span>Rating</span><select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value={5}>5 — Excellent</option><option value={4}>4 — Very good</option><option value={3}>3 — Good</option><option value={2}>2 — Needs improvement</option><option value={1}>1 — Poor</option></select></div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="How useful was this training for your work?"/><button className="btn btn-secondary btn-block" disabled={!feedback.trim()} onClick={()=>{submitFeedback(course.id,rating,feedback);setFeedback("")}}>Submit feedback</button>{db.feedback.find(f=>f.traineeId===trainee?.id&&f.courseId===course.id)&&<small>✓ Your feedback is saved</small>}</div><div className="discussion-box"><strong>Question / discussion</strong><textarea placeholder="Ask the trainer a question..."/><button className="btn btn-secondary" onClick={()=>alert("Question sent to trainer in prototype.")}>Send question</button></div></aside>
    </div>
  </>
}