import { Badge, ConfirmButton, EmptyState, PageHeader } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function Recommendations(){
  const {db,currentUser,recommendationsForCurrentTrainee,requestEnrollment}=useApp();const trainee=db.trainees.find(t=>t.userId===currentUser?.id);const recs=recommendationsForCurrentTrainee();const latest=db.competencyResults.find(r=>r.traineeId===trainee?.id);
  return <><PageHeader title="Personalized Recommendations" subtitle="Transparent course and trainer matching based on your latest competency gap."/>
    {latest&&<section className="gap-banner"><div><span>Identified development need</span><strong>{latest.subject}: {latest.currentLevel} → {latest.requiredLevel}</strong></div><div className="chip-row">{latest.missingCompetencies.map(x=><span className="chip" key={x}>{x}</span>)}</div></section>}
    {recs.length?<div className="recommend-grid">{recs.map((r,i)=>{const existing=db.enrollments.find(e=>e.traineeId===trainee?.id&&e.courseId===r.course.id&&e.status!=="rejected");return <article className="recommend-card" key={r.course.id}><div className="recommend-rank">#{i+1}</div><div className="match-score"><strong>{r.match}%</strong><span>match</span></div><div className="recommend-main"><div className="course-top"><span>{r.course.subject}</span><Badge tone="blue">{r.course.level}</Badge></div><h2>{r.course.title}</h2><p>{r.course.description}</p><div className="trainer-strip"><div className="avatar">{r.trainer?.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><strong>{r.trainer?.name}</strong><span>{r.trainer?.verified?"Admin Verified · ":""}★ {r.trainer?.rating} · {r.trainer?.availability}</span></div></div><div className="why-box"><strong>Why this was recommended</strong><ul>{r.reasons.map(x=><li key={x}>{x}</li>)}</ul><div className="match-breakdown">{r.breakdown.map(b=><div key={b.key}><div><span>{b.label}</span><b>{b.points}/{b.max}</b></div><div className="micro-bar"><i style={{width:`${b.points/b.max*100}%`}}/></div><small>{b.explanation}</small></div>)}</div></div><div className="recommend-footer"><span>{r.course.durationHours} learning hours · {r.course.startDate}</span>{existing?<Badge tone={existing.status==="approved"?"green":"amber"}>{existing.status}</Badge>:<ConfirmButton label="Enroll Now" confirmText={`Request enrollment in "${r.course.title}"?`} onConfirm={()=>requestEnrollment(r.course.id)}/>}</div></div></article>})}</div>:<EmptyState title="Run a competency check first" body="Recommendations appear after the system identifies a role-based competency gap."/>}
  </>
}