import { FormEvent, useEffect, useMemo, useState } from "react";
import { Badge, ConfirmButton, PageHeader, SearchBox } from "../../components/UI";
import { useApp } from "../../context/AppContext";
import { Role } from "../../types";

const departments=["Weather Forecasting","Satellite Meteorology","Radar Meteorology","Climate Research & Services","Hydrometeorology","Agricultural Meteorology","Instrumentation","Seismology","Training Division","Administration"];
export default function AdminUsers(){
  const {db,approveUser,toggleUserStatus,changeUserRole,createUser}=useApp(); const [q,setQ]=useState(""); const [role,setRole]=useState("all"); const [status,setStatus]=useState("all"); const [page,setPage]=useState(1); const [showAdd,setShowAdd]=useState(false); const [message,setMessage]=useState(""); const pageSize=8;
  const [form,setForm]=useState({name:"",email:"",password:"Demo@123",role:"trainee" as Role,department:"Weather Forecasting",designation:"Scientific Assistant",employeeId:""});
  const rows=useMemo(()=>db.users.filter(u=>(role==="all"||u.role===role)&&(status==="all"||u.status===status)&&`${u.name} ${u.email} ${u.department} ${u.employeeId||""}`.toLowerCase().includes(q.toLowerCase())),[db.users,q,role,status]);
  const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)); const pageRows=rows.slice((page-1)*pageSize,page*pageSize); useEffect(()=>setPage(1),[q,role,status]);
  const submit=(e:FormEvent)=>{e.preventDefault();const r=createUser(form);setMessage(r.message);if(r.ok){setForm({...form,name:"",email:"",employeeId:"",password:"Demo@123"});setShowAdd(false)}};
  return <><PageHeader title="Identity, Approval & Role Management" subtitle="Create Admin, Trainer and Trainee accounts; review registrations and control IMD role access." actions={<button className="btn btn-primary" onClick={()=>setShowAdd(!showAdd)}>+ Add user</button>}/>
    {showAdd&&<section className="panel imd-form-panel"><div className="panel-title"><div><span className="section-kicker">ADMIN PROVISIONING</span><h3>Create IMD portal account</h3></div><Badge tone="blue">Immediate activation</Badge></div><form className="form-grid" onSubmit={submit}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Official email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Employee / Staff ID<input value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} placeholder="IMD-XXXX"/></label><label>Portal role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})}><option value="admin">Admin</option><option value="trainer">Trainer</option><option value="trainee">Trainee</option></select></label><label>IMD Division<select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Designation<input required value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></label><label>Temporary password<input required minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="form-actions"><button className="btn btn-primary">Create & activate account</button><button type="button" className="btn btn-secondary" onClick={()=>setShowAdd(false)}>Cancel</button></div></form>{message&&<p className="form-message">{message}</p>}</section>}
    <div className="toolbar"><SearchBox value={q} onChange={setQ} placeholder="Search name, email, division or employee ID"/><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option><option>trainer</option><option>trainee</option><option>admin</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option>pending</option><option>active</option><option>inactive</option><option>rejected</option></select></div>
    <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>IMD Division</th><th>Status</th><th>Registered</th><th>Actions</th></tr></thead><tbody>{pageRows.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}{u.employeeId?` · ${u.employeeId}`:""}</small></td><td className="capitalize"><select className="role-select" value={u.role} onChange={e=>changeUserRole(u.id,e.target.value as Role)}><option value="admin">admin</option><option value="trainer">trainer</option><option value="trainee">trainee</option></select></td><td>{u.department}<small>{u.designation}</small></td><td><Badge tone={u.status==="active"?"green":u.status==="pending"?"amber":u.status==="rejected"?"red":"gray"}>{u.status}</Badge></td><td>{u.createdAt}</td><td><div className="table-actions">{u.status==="pending"?<><ConfirmButton label="Approve" confirmText={`Approve ${u.name} as ${u.role}?`} onConfirm={()=>approveUser(u.id,true)}/><ConfirmButton label="Reject" className="btn btn-danger-soft" confirmText={`Reject ${u.name}'s registration?`} onConfirm={()=>approveUser(u.id,false)}/></>:<ConfirmButton label={u.status==="active"?"Deactivate":"Activate"} className="btn btn-secondary" confirmText={`Change account status for ${u.name}?`} onConfirm={()=>toggleUserStatus(u.id)}/>}</div></td></tr>)}</tbody></table></div><div className="pagination"><span>Showing {rows.length?(page-1)*pageSize+1:0}-{Math.min(page*pageSize,rows.length)} of {rows.length}</span><div><button className="btn btn-secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {totalPages}</span><button className="btn btn-secondary" disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section>
  </>;
}
