import { FormEvent, useState } from "react";
import { Badge, ConfirmButton, PageHeader, SearchBox } from "../../components/UI";
import { useApp } from "../../context/AppContext";
import { Course, Level } from "../../types";

const blank = {title:"",code:"",department:"Meteorology",subject:"",level:"Intermediate" as Level,trainerId:"",description:"",durationHours:12,startDate:"",endDate:"",enrollmentLimit:30};

export default function AdminCourses(){
  const {db,setCourseStatus,decideEnrollment,createCourse,updateCourse}=useApp();
  const [q,setQ]=useState(""); const [editing,setEditing]=useState<Course|null>(null); const [showForm,setShowForm]=useState(false);
  const [form,setForm]=useState(blank);
  const courses=db.courses.filter(c=>`${c.title} ${c.subject} ${c.code}`.toLowerCase().includes(q.toLowerCase()));
  const trainer=(id:string)=>db.trainers.find(t=>t.id===id)?.name||"Unassigned";

  const openCreate=()=>{setEditing(null);setForm({...blank,trainerId:db.trainers[0]?.id||""});setShowForm(true)};
  const openEdit=(c:Course)=>{setEditing(c);setForm({title:c.title,code:c.code,department:c.department,subject:c.subject,level:c.level,trainerId:c.trainerId,description:c.description,durationHours:c.durationHours,startDate:c.startDate,endDate:c.endDate,enrollmentLimit:c.enrollmentLimit});setShowForm(true)};
  const submit=(e:FormEvent)=>{e.preventDefault();
    if(editing){ updateCourse(editing.id,{...form}); }
    else { createCourse({...form,objectives:["Admin-created capacity building course"],modules:[{id:`m-${Date.now()}`,title:"Module 1",lessons:[{id:`l-${Date.now()}`,title:"Introduction",type:"video",durationMin:20,resource:"Pending upload"}]}]}); }
    setShowForm(false);
  };

  return <><PageHeader title="Course Management" subtitle="Create, edit, review, publish and archive capacity-building courses." actions={<button className="btn btn-primary" onClick={openCreate}>+ Create Course</button>}/>
    {showForm&&<section className="panel course-admin-form"><div className="panel-head"><div><h3>{editing?"Edit course":"Create course"}</h3><p>{editing?"Update course metadata and trainer assignment.":"New Admin-created courses start in pending state and can be published after review."}</p></div><button className="btn btn-secondary" onClick={()=>setShowForm(false)}>Close</button></div><form className="stack-form" onSubmit={submit}><div className="form-grid two"><label>Course title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Course code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></label><label>Department<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} required/></label><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></label><label>Level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value as Level})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Trainer<select value={form.trainerId} onChange={e=>setForm({...form,trainerId:e.target.value})} required><option value="">Select trainer</option>{db.trainers.map(t=><option key={t.id} value={t.id}>{t.name} {t.verified?"✓":""}</option>)}</select></label><label>Start date<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label>Duration (hours)<input type="number" min={1} value={form.durationHours} onChange={e=>setForm({...form,durationHours:Number(e.target.value)})}/></label><label>Enrollment limit<input type="number" min={1} value={form.enrollmentLimit} onChange={e=>setForm({...form,enrollmentLimit:Number(e.target.value)})}/></label></div><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary">{editing?"Save changes":"Create course proposal"}</button></form></section>}
    <div className="toolbar"><SearchBox value={q} onChange={setQ} placeholder="Search course, subject or code"/></div>
    <section className="panel table-panel"><div className="panel-head"><div><h3>Courses</h3><p>{courses.length} records</p></div></div><div className="table-scroll"><table><thead><tr><th>Course</th><th>Trainer</th><th>Level</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td><strong>{c.title}</strong><small>{c.code} · {c.department}</small></td><td>{trainer(c.trainerId)}</td><td>{c.level}</td><td>{c.startDate||"TBD"}<small>to {c.endDate||"TBD"}</small></td><td><Badge tone={c.status==="published"?"green":c.status==="pending"?"amber":c.status==="archived"?"gray":"blue"}>{c.status}</Badge></td><td><div className="table-actions"><button className="btn btn-secondary" onClick={()=>openEdit(c)}>Edit</button>{c.status==="pending"&&<ConfirmButton label="Publish" confirmText={`Approve and publish "${c.title}"?`} onConfirm={()=>setCourseStatus(c.id,"published")}/>} {c.status==="published"&&<ConfirmButton label="Archive" className="btn btn-secondary" confirmText={`Archive "${c.title}"?`} onConfirm={()=>setCourseStatus(c.id,"archived")}/>} {c.status==="archived"&&<ConfirmButton label="Republish" confirmText={`Republish "${c.title}"?`} onConfirm={()=>setCourseStatus(c.id,"published")}/>}</div></td></tr>)}</tbody></table></div></section>
    <section className="panel table-panel"><div className="panel-head"><div><h3>Enrollment approval queue</h3><p>Requests requiring Admin decision</p></div></div><div className="table-scroll"><table><thead><tr><th>Trainee</th><th>Course</th><th>Requested</th><th>Status</th><th>Decision</th></tr></thead><tbody>{db.enrollments.filter(e=>e.status==="requested").map(e=><tr key={e.id}><td>{db.trainees.find(t=>t.id===e.traineeId)?.name}</td><td>{db.courses.find(c=>c.id===e.courseId)?.title}</td><td>{e.requestedAt}</td><td><Badge tone="amber">requested</Badge></td><td><div className="table-actions"><ConfirmButton label="Approve" confirmText="Approve this enrollment request?" onConfirm={()=>decideEnrollment(e.id,true)}/><ConfirmButton label="Reject" className="btn btn-danger-soft" confirmText="Reject this enrollment request?" onConfirm={()=>decideEnrollment(e.id,false)}/></div></td></tr>)}{!db.enrollments.some(e=>e.status==="requested")&&<tr><td colSpan={5} className="table-empty">No pending enrollment requests.</td></tr>}</tbody></table></div></section>
  </>
}